site_name: AutoDispose
repo_name: AutoDispose
repo_url: https://github.com/uber/AutoDispose
site_description: "Automatic binding+disposal of RxJava 2 streams."
site_author: Uber Technologies
remote_branch: gh-pages

copyright: 'Copyright &copy; 2019 Uber Technologies'

theme:
  name: 'material'
  favicon: images/uber_oss_logo.png
  logo: images/uber_oss_logo.png
  palette:
    primary: 'white'
    accent: 'white'

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - 'Overview': index.md
  - '2.X API':
    - 'autodispose': 2.x/autodispose/autodispose2/index.html
    - 'autodispose-android': 2.x/autodispose-android/autodispose2.android/index.html
    - 'autodispose-androidx-lifecycle': 2.x/autodispose-androidx-lifecycle/autodispose2.androidx.lifecycle/index.html
    - 'autodispose-lifecycle': 2.x/autodispose-lifecycle/autodispose2.lifecycle/index.html
    - 'autodispose-interop-coroutines': 2.x/coroutines/autodispose2.interop.coroutines/index.html
  - 'Error Prone': error-prone.md
  - 'Lint Check': lint-check.md
  - 'Changelog' : changelog.md
  - 'Migrating from 0.2.0 to 0.3.0': migrating-020-030.md
  - 'Migrating from 0.4.0 to 0.5.0': migrating-040-050.md
  - 'Migrating from 1.x to 2.x': migrating-1x-2x.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code-of-conduct.md
